- name: Install apache on vm3
  hosts: apache_hosts
  gather_facts: no

  tasks:
    - name: Install apache server
      package:
        name: apache2  
        state: present

    - name: Start Apache service and enable it on boot
      service:
        name: apache2  
        state: started
        enabled: yes

    - name: Check if Apache service is enabled
      command: systemctl is-enabled apache2
      register: apache_enabled
      ignore_errors: true 

    - name: Print Apache service status
      debug:
        msg: "Apache service is {{ 'enabled' if apache_enabled.rc == 0 else 'not enabled' }}"
